repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
-   repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
    -   id: black
        types: [python]
-   repo: local
    hooks:
    -   id: go-vet
        name: go-vet
        entry: go vet
        files: cmd/app/main.go
        language: system
        types: [go]
    - id: pylint
      name: pylint
      entry: poetry run pylint app/
      language: system
      pass_filenames: false
      types: [python]
- repo: https://github.com/dnephin/pre-commit-golang
  rev: master
  hooks:
    - id: go-fmt
    - id: go-imports
    - id: go-cyclo
      args: [-over=15]
    - id: validate-toml
    - id: golangci-lint
    - id: go-critic
    - id: go-unit-tests
    - id: go-build
    - id: go-mod-tidy
  types: [go]
