repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
        types: [python]
-   repo: local
    hooks:
    -   id: go-vet
        name: go-vet
        entry: go vet
        files: cmd/app/main.go
        language: system
        types: [go]
    - id: pylint
      name: pylint
      entry: poetry run pylint app/
      language: system
      pass_filenames: false
      types: [python]
- repo: https://github.com/dnephin/pre-commit-golang
  rev: v0.5.1
  hooks:
    - id: go-fmt
      types: [go]
    - id: go-imports
      types: [go]
    - id: go-cyclo
      args: [-over=15]
      types: [go]
    - id: validate-toml
    - id: golangci-lint
      types: [go]
    - id: go-critic
      types: [go]
    - id: go-unit-tests
      types: [go]
    - id: go-build
      types: [go]
    - id: go-mod-tidy
      types: [go]
- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  rev: v9.1.0
  hooks:
    - id: commitlint
      stages: [commit-msg]
      additional_dependencies: ['@commitlint/config-conventional']
