version: '2'

services:
    mosquitto:
      image: eclipse-mosquitto
      ports:
        - 1883:1883
      volumes:
        - ./.docker/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
        - ./.docker/mosquitto/users.txt:/mosquitto/config/users.txt:ro
      restart: always
      command: mosquitto -p 1883 -v -c /mosquitto/config/mosquitto.conf
    tcp2mqtt:
      build: .
      environment:
        - CONFIG_PATH=/opt/config.yaml
        - BROKER=tcp://mosquitto:1883
      ports:
        - 7777:7777
      command:
        # - ./app
        # - -topic=v1/devices/me/telemetry
        # - -broker=tcp://mqtt.varadise.cloud:8883
        - sh
        - -c
        - "./app -topic=v1/devices/me/telemetry -broker=$$BROKER"
      volumes:
        - .:/opt
      depends_on:
        - mosquitto
      restart: always
